version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - data:/var/lib/postgresql/data1
  feedservice:
    build:
      context: ./newsfeedService
      dockerfile: Dockerfile
    environment:
        DB_USER: "postgres"
        DB_PASS: "password"
        DB_HOST: "database:5432"
    depends_on:
      - database
    networks:
      - mynet
    ports:
    - "8880:8880"
  ingestionservice:
      build:
        context: ./feedIngestionService
        dockerfile: Dockerfile
      environment:
          DB_USER: "postgres"
          DB_PASS: "password"
          DB_HOST: "database:5432"
      depends_on:
        - database
      networks:
        - mynet
volumes:
  data:

networks:
  mynet:
    driver: bridge
